### ISSUE TITLE
Don't have org-zettel-ref-run-python-script

### ISSUE THREAD

**Issue by yellowfishee** [yibie/org-zettel-ref-mode#9]
如题，在org-zettel-ref-mode文件中没有该命令，但是在org-zettel-ref-mode,backup中有该命令，请问是下版本还有关于该功能的改动吗？
![image](https://github.com/user-attachments/assets/9f7e4f53-274f-4ef0-81ef-a40162736d42)

**Comment by yibie** [comment]
版本暂时回滚。你如果要用，暂时可以用命令行直接运行 py 脚本。这个命令是重要功能，会补上。

**Comment by yellowfishee** [comment]
> 版本暂时回滚。你如果要用，暂时可以用命令行直接运行 py 脚本。这个命令是重要功能，会补上。

我从backup里复制到了我的文件里，可以走通函数。
我使用的是windows，ebook_convert无法将epub转md或org，所以我使用了pandoc，但是我发现您提供的脚本中默认使用的是ebook_convert的方式。
如果时间充裕，您可以考虑下windows直接使用pandoc

**Comment by yibie** [comment]
Mark。Windows 现在有命令行工具，应该可以直接运行 ebook-convert 来转换文档。请问，你在运行的时候，有看到什么错误提示吗？

**Comment by yellowfishee** [comment]
epub 2 org
D:\ref>ebook-convert 认知觉醒.epub rzjx.org
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\ebooks\conversion\cli.py", line 390, in main
  File "calibre\ebooks\conversion\cli.py", line 342, in create_option_parser
  File "calibre\ebooks\conversion\plumber.py", line 775, in __init__
ValueError: No plugin to handle output format: org

epub to md
D:\ref>ebook-convert 认知觉醒.epub rzjx.md
Traceback (most recent call last):
  File "runpy.py", line 198, in _run_module_as_main
  File "runpy.py", line 88, in _run_code
  File "site.py", line 83, in <module>
  File "site.py", line 78, in main
  File "site.py", line 50, in run_entry_point
  File "calibre\ebooks\conversion\cli.py", line 390, in main
  File "calibre\ebooks\conversion\cli.py", line 342, in create_option_parser
  File "calibre\ebooks\conversion\plumber.py", line 775, in __init__
ValueError: No plugin to handle output format: md

pandoc 认知觉醒.epub -o rzjx.org 能正常转换成org文件

**Comment by yibie** [comment]
Done。更新到最新版本。
